### ISSUE TITLE
setup_cg.sh installation issues

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/genome_runner#104]
When everything is installed from .deb packages, there are numerous errors. So, we are back to installing python packages through apt-get.

When installing main GR as 'sudo python setup.py install', that is, as a package, OLD interface shows up! Same when installing in developer mode.

When installing main GR as 'sudo python setup.py install develop -d /usr/local/lib/python2.7/dist-packages/', that is, in developer mode, error arises, below. Cured by removing 'install_requires' section from 'setup.py':

int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-JSD6vn/numpy-1.9.2/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.o: In function `main':
/tmp/easy_install-JSD6vn/numpy-1.9.2/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
 int exp (void);
     ^
_configtest.c:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
_configtest.c:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    "redis == 2.10.0"
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 73, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 101, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 358, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 574, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 625, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 671, in process_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 563, in resolve
    entry = dist.location
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 801, in best_match
    
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 813, in obtain
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 593, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 623, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 809, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1015, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1000, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 50, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 100, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 52, in <lambda>
  File "setup.py", line 251, in <module>
    
  File "setup.py", line 243, in setup_package
    
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/core.py", line 169, in setup
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 177, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/command/egg_info.py", line 10, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/command/build_src.py", line 153, in run
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/command/build_src.py", line 170, in build_sources
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
  File "/tmp/easy_install-JSD6vn/numpy-1.9.2/numpy/distutils/command/build_src.py", line 386, in generate_sources
  File "numpy/core/setup.py", line 432, in generate_config_h
    
  File "numpy/core/setup.py", line 42, in check_types
    
  File "numpy/core/setup.py", line 293, in check_types
    
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

**Comment by mdozmorov** [comment]
dbcreator_encode is not installed as a module.
